services:
    database:
        image: mariadb:latest
        container_name: zox_database
        environment:
            - MYSQL_PASSWORD=$DATABASE_PASSWORD
            - MYSQL_ROOT_PASSWORD=$DATABASE_PASSWORD
            - MYSQL_USER=$DATABASE_USER
            - MYSQL_DATABASE=zox
        ports:
            - '3306:3306'
    redis:
        image: redis:latest
        container_name: zox_redis
        command: redis-server --requirepass $REDIS_PASSWORD
        ports:
            - '6379:6379'
